services:
  - name: rabbitmq
    type: web
    plan: free
    image: rabbitmq
    env: []
    ports:
      - 5672:5672

  - name: selenium
    type: web
    plan: free
    image: selenium/standalone-chrome:latest
    env: []
    ports: []

  - name: producer
    type: web
    plan: free
    runtime: go
    image: fabrice45/assignments_producer:latest
    env:
      - key: RABBITMQ_URL
        value: amqp://guest:guest@rabbitmq:5672/
    envFrom:
      - service: rabbitmq
    ports:
      - 3000:3000

  - name: umucyo-consumer
    type: web
    plan: free
    runtime: node
    image: fabrice45/umucyo_consumer:latest
    env:
      - key: SELENIUM_HOST
        value: selenium
      - key: SELENIUM_PORT
        value: "4444"
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672/
    envFrom:
      - service: rabbitmq
    dependsOn:
      - name: rabbitmq
      - name: selenium
    ports:
      - 3001:3001

  - name: verama-consumer
    type: web
    plan: free
    runtime: python
    image: fabrice45/verama_consumer:latest
    env:
      - key: RABBITMQ_HOST
        value: rabbitmq
    envFrom:
      - service: rabbitmq
    dependsOn:
      - name: rabbitmq
      - name: producer
    ports:
      - 3002:3002

  - name: assignments
    type: web
    plan: free
    runtime: go
    image: fabrice45/assignments:latest
    env: []
    ports:
      - 4001:4001
