services:
  - name: rabbitmq
    image: 
      url: rabbitmq:3
    env: docker
    plan: starter
    type: web

  - name: selenium
    image: 
      url: selenium/standalone-chrome:latest
    plan: starter
    type: web

  - name: producer
    image: 
      url: fabrice45/assignments_producer:latest
    envVars:
      - key: RABBITMQ_URL
        value: amqp://guest:guest@rabbitmq:5672/
    plan: starter
    type: web

  - name: umucyo-consumer
    image: 
      url: fabrice45/umucyo_consumer:latest
    envVars:
      - key: SELENIUM_HOST
        value: selenium
      - key: SELENIUM_PORT
        value: "4444"
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672/
    dependsOn:
      - name: rabbitmq
      - name: selenium
    plan: starter
    type: web

  - name: verama-consumer
    image: 
      url: fabrice45/verama_consumer:latest
    envVars:
      - key: RABBITMQ_HOST
        value: rabbitmq
    dependsOn:
      - name: rabbitmq
      - name: producer
    plan: starter
    type: web

  - name: assignments
    image: 
      url: fabrice45/assignments:latest
    plan: starter
    type: web
