services:
  - name: rabbitmq
    image: 
      name: rabbitmq
      tag: 3
    env: []
    ports:
      - 5672:5672
    plan: free
    type: web

  - name: selenium
    image: 
      name: selenium/standalone-chrome
      tag: latest
    env: []
    ports: []
    plan: free
    type: web

  - name: producer
    image: 
      name: fabrice45/assignments_producer
      tag: latest
    env:
      - key: RABBITMQ_URL
        value: amqp://guest:guest@rabbitmq:5672/
    envFrom:
      - service: rabbitmq
    ports:
      - 3000:3000
    plan: free
    type: web

  - name: umucyo-consumer
    image: 
      name: fabrice45/umucyo_consumer
      tag: latest
    env:
      - key: SELENIUM_HOST
        value: selenium
      - key: SELENIUM_PORT
        value: "4444"
      - key: RABBITMQ_URL
        value: amqp://rabbitmq:5672/
    envFrom:
      - service: rabbitmq
    dependsOn:
      - name: rabbitmq
      - name: selenium
    ports:
      - 3001:3001
    plan: free
    type: web

  - name: verama-consumer
    image: 
      name: fabrice45/verama_consumer
      tag: latest
    env:
      - key: RABBITMQ_HOST
        value: rabbitmq
    envFrom:
      - service: rabbitmq
    dependsOn:
      - name: rabbitmq
      - name: producer
    ports:
      - 3002:3002
    plan: free
    type: web

  - name: assignments
    image: 
      name: fabrice45/assignments
      tag: latest
    env: []
    ports:
      - 4001:4001
    plan: free
    type: web
